name: Building and linting the project
run-name: ${{ github.actor }} created ${{ github.event_name }}

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Кэширование зависимостей
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      # Шаг 3: Установка Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Шаг 4: Установка зависимостей с помощью npm ci
      - name: Install dependencies
        run: npm ci

      # Шаг 5: Линтинг проекта
      - name: Linting project
        run: npm run lint

      # Шаг 6: Сборка проекта
      - name: Build project
        run: npm run build

      # Шаг 8: Публикация артефактов сборки (если применимо)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      # Шаг 9: Вывод сообщения о запуске действия
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."