name: Building and linting the project
run-name: ${{ github.actor }} made a new push

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      - name: Linting project
        run: npm run lint

      # Шаг 4: Сборка проекта
      - name: Build project
        run: npm run build

      # Шаг 5: Вывод сообщения о запуске действия
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
